enum { FLOPPY_BACKUP = 0, FLOPPY_RESTORE, FS_BACKUP, FS_RESTORE, FS_VERIFY,
       LOG_FILE, DEL_LOG_ENTRY, UPDATE_LOG, CREATE_NEW_LOG, QUIT_VBS,

       LOG_WINDOW, LOG_HORIZ, LOG_VERT,
       LOG_ARROW_LEFT, LOG_ARROW_RIGHT, LOG_ARROW_UP, LOG_ARROW_DOWN
};
#define FILLCOLOR 1
#define BCOLOR    2

