enum { FLOPPY_BACKUP = 0, FLOPPY_RESTORE, FS_BACKUP, FS_RESTORE, FS_VERIFY,
       NEW_LOG, LOAD_LOG, SAVE_LOG, SETTINGS, QUIT_VBS, DEL_LOG_ENTRY,
       LOG_ACTIONS, LOG_WINDOW, LOG_HORIZ, LOG_VERT
};

